### ISSUE TITLE
Emacs Goodies fails to compile

### ISSUE THREAD

**Issue by seanfisk** [dimitri/emacs-kicker#2]
Hi Dimitri,

I know this isn't your issue directly, but I'm getting this error which I believe is caused by Emacs Goodies:

```
Leaving directory `~/'

Compiling file /home/sean/.emacs.d/el-get/.loaddefs.el at Wed Jul 27 21:44:02 2011
Entering directory `/home/sean/.emacs.d/el-get/'
.loaddefs.el:1823:836:Warning: reference to free variable
    `pretty-control-l-mode'
.loaddefs.el:1823:1142:Warning: assignment to free variable
    `pretty-control-l-mode'

In end of data:
.loaddefs.el:2562:1:Warning: the function `pretty-control-l-mode' is not known
    to be defined.
```

I'm using the apt version of Emacs 23 in Ubuntu 10.04. If you have any advice, it would be much appreciated!

**Comment by dimitri** [comment]
I guess it got fixed meanwhile. Sorry not to have answered before, I'm closing the issue now. Feel free to re-open if some work is still needed.
