### ISSUE TITLE
osx alt key not functional

### ISSUE THREAD

**Issue by hooleyhoop** [dimitri/emacs-kicker#8]
i'm using railwaycat/emacs-mac-port on osx. Command key is meta but i still can't type the optional chars on my uk keyboard e.g. opt-1=¡, opt-2=€, opt-3=#, opt-4=¢, opt-5=∞ etc..

I tried changing (setq mac-option-modifier 'none))
to (setq mac-option-modifier nil))

and that seemed to fix it. Thanks

**Comment by dimitri** [comment]
Works for me with emacsformacosx.
