### ISSUE TITLE
Set font fail on daemon mode or terminal

### ISSUE THREAD

**Issue by fzerorubigd** [dimitri/emacs-kicker#9]
I use emacs kicker in normal emacs (Archlinux , emacs 24, latest) and every thing is ok, I have installed Inconsolata font (The GUI mode is Ok and the font is set) but with -nw or --daemon the result is : 

```
Warning (initialization): An error occurred while loading `/home/f0rud/.emacs.d/init.el':

error: Font not available, #<font-spec nil nil Inconsolata nil nil nil nil nil 14.0 nil nil nil ((:name .\
 Inconsolata-14) (user-spec . Inconsolata-14))>

```

I can set the font with `(set-default-font "Inconsolata-14")` but not with  `(set-face-font 'default "Inconsolata-14")` And I don't know if this is emacs-kicker related or not :)

Thanks!

**Comment by dimitri** [comment]
I'd be surprised if it were emacs-kicker related, so closing now. Sorry don't have time now to dig up some font related docs, find references about GUI problems when starting a daemon in _no window_ mode.
